participantes = ["robarros@gmail.com",
"marcioacosta@gmail.com",
"camanducci@gmail.com",
"jhkpereira@gmail.com",
"fabricio.candido@gmail.com",
"willianccs@gmail.com",
"robsonguedes76@gmail.com",
"rafael@rfbarbosa.com",
"henriqueserrat@gmail.com",
"luanrafael@outlook.com",
"iromato@gmail.com",
"alexandrems.info@gmail.com",
"lfam82@gmail.com",
"kaio.22.nascimento@gmail.com",
"diogoalvescavalcante@gmail.com",
"guilherme.amadi@gmail.com",
"ericssondelima@gmail.com",
"erickdavi@gmail.com",
"danieljones028@gmail.com",
"rodrigo.c.belmonte@gmail.com",
"vinirgomessp@gmail.com",
"fnferri@hotmail.com",
"viniciusmaia@gmail.com",
"isaacjbneto@gmail.com",
"acvecchia@hotmail.com",
"jhonatancmorais@gmail.com",
"diego.milhomes@gmail.com",
"renato.bardi@live.com",
"aloisiobilck@gmail.com"]

puts participantes.sample